### ISSUE TITLE
How decompress the smaple files

### ISSUE THREAD

**Issue by hihtcho** [mhwong2007/GEE#2]
Dear 

Thank you for your effort !

I've some problems. I downloaded some processed data on the site. 

but these files have to decompress or unpack or ???/ to parquet file....

I don't know how to change or unpack the files ..... please help me. 

model_input/train.model_input.parquet 
model_input/test.model_input.parquet

**Comment by munhouiani** [comment]
These are parquet files.

You can either read them with Pandas or by Spark.

**Comment by hihtcho** [comment]
Thank you for your kindly reply!
But I'm not familar about parquet...

Your data is compressed gz files.
As i know parquet file is a single file.... right?
1) Shoud I decompress .gz file ? How???

[1653522258538](https://user-images.githubusercontent.com/51772648/170387143-6a0fa04b-745c-48c0-b77b-e563650fffd3.png)

2)  Using commercial zip application  or python gz , all file is decomposed many files in directory.   ( 0000 ~.par, 0001 ~.par ......)
3) I'm sorry but may i have some sample code  for using .gz for applying your code?

I'm so sorry....about  confuzzing...ㅠㅠ

**Comment by munhouiani** [comment]
Hi,

1. Yes, you should decompress .gz file, you are doing right.
2. This is normal. I used Spark to generate this output, and Spark will write multiple parquet files due to its distributed computing mechanism.
3. https://github.com/munhouiani/GEE/blob/master/evaluation.ipynb actually shows you how to work with the parquet files. Note that `model_input/test.model_input.parquet` in the code is not a file, but a directory containing many files.

**Comment by hihtcho** [comment]
data_path = 'model_input/test.model_input.parquet'

reader = make_reader(
    Path(data_path).absolute().as_uri(), 
    reader_pool_type='process', workers_count=num_cores,
    pyarrow_serialize=True, num_epochs=1
)
dataloader = DataLoader(reader, batch_size=300, shuffling_queue_capacity=4096)


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_4904\2644312662.py in <module>
      5     #Path(data_path).absolute(),
      6     reader_pool_type='process', workers_count=num_cores,
----> 7     pyarrow_serialize=True, num_epochs=1
      8 )
      9 dataloader = DataLoader(reader, batch_size=300, shuffling_queue_capacity=4096)

~\.conda\envs\gee\lib\site-packages\petastorm\reader.py in make_reader(dataset_url, schema_fields, reader_pool_type, workers_count, pyarrow_serialize, results_queue_size, shuffle_row_groups, shuffle_row_drop_partitions, predicate, rowgroup_selector, num_epochs, cur_shard, shard_count, cache_type, cache_location, cache_size_limit, cache_row_size_estimate, cache_extra_settings, hdfs_driver, transform_spec)
    132 
    133     try:
--> 134         dataset_metadata.get_schema_from_dataset_url(dataset_url, hdfs_driver=hdfs_driver)
    135     except PetastormMetadataError:
    136         raise RuntimeError('Currently make_reader supports reading only Petastorm datasets. '

~\.conda\envs\gee\lib\site-packages\petastorm\etl\dataset_metadata.py in get_schema_from_dataset_url(dataset_url_or_urls, hdfs_driver)
    393     fs, path_or_paths = get_filesystem_and_path_or_paths(dataset_url_or_urls, hdfs_driver)
    394 
--> 395     dataset = pq.ParquetDataset(path_or_paths, filesystem=fs, validate_schema=False, metadata_nthreads=10)
    396 
    397     # Get a unischema stored in the dataset metadata.

~\.conda\envs\gee\lib\site-packages\pyarrow\parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema, filters, metadata_nthreads, read_dictionary, memory_map, buffer_size, partitioning, use_legacy_dataset)
   1270          self.metadata_path) = _make_manifest(
   1271              path_or_paths, self.fs, metadata_nthreads=metadata_nthreads,
-> 1272              open_file_func=partial(_open_dataset_file, self._metadata)
   1273         )
   1274 

~\.conda\envs\gee\lib\site-packages\pyarrow\parquet.py in _make_manifest(path_or_paths, fs, pathsep, metadata_nthreads, open_file_func)
   1465             if not fs.isfile(path):
   1466                 raise OSError('Passed non-file path: {}'
-> 1467                               .format(path))
   1468             piece = ParquetDatasetPiece(path, open_file_func=open_file_func)
   1469             pieces.append(piece)

OSError: Passed non-file path: /c:/workspace/GEE/model_input/test.model_input.parquet

-------------------------
pyarrow doesn't accept a directory ...

**Comment by munhouiani** [comment]
No, pyarrow does accept a directory:

```python
>>> import pyarrow.parquet as pq
>>> path = 'test.model_input.parquet'
>>> table = pq.read_table(path)
>>> df = table.to_pandas()
>>> df.head()
           time_window          src_ip                                            feature       label
0  2016-07-31 10:03:00    211.35.66.38  b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\...  background
1  2016-07-31 10:03:00    211.36.25.22  b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\...  background
2  2016-07-31 10:03:00   211.36.63.107  b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\...  background
3  2016-07-31 10:03:00  211.37.135.153  b"PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\...  background
4  2016-07-31 10:03:00   211.37.135.54  b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\...  background
```

and `test.model_input.parquet` here is a directory:

```python
>>> import os
>>> os.listdir(path)
['.part-00004-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', '_common_metadata', '.part-00008-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00001-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', 'part-00011-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00007-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00006-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', 'part-00010-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00003-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00007-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00000-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', '.part-00011-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00000-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00005-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', '.part-00009-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00005-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', 'part-00009-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', 'part-00002-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00006-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00008-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '_SUCCESS', 'part-00003-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet', '.part-00002-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', '.part-00001-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', '.part-00010-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet.crc', 'part-00004-46abc78c-24e4-40e4-b9a8-cf6951846d95-c000.snappy.parquet']
```

**Comment by hihtcho** [comment]
Thank you for your reply...
It may occur my python environmemt.....
above code is operated well... but evaluation.ipynb still not work...
========================================================
reader = make_reader(
    Path(data_path).absolute().as_uri(), 
    reader_pool_type='process', workers_count=num_cores,
    pyarrow_serialize=True, num_epochs=1
)
------------------------------------------------------------------------------------------------
~\.conda\envs\gee\lib\site-packages\pyarrow\parquet.py in _make_manifest(path_or_paths, fs, pathsep, metadata_nthreads, open_file_func)
   1469             if not fs.isfile(path):
   1470                 raise OSError('Passed non-file path: {}'
-> 1471                               .format(path))
   1472             piece = ParquetDatasetPiece(path, open_file_func=open_file_func)
   1473             pieces.append(piece)

OSError: Passed non-file path: /c:/workspace/GEE/model_input/test.model_input.parquet

**Comment by munhouiani** [comment]
I am not familiar with Windows environment, based on your error message, can you check this is a valid path?

```python
import os

os.listdir('/c:/workspace/GEE/model_input/test.model_input.parquet')
```

**Comment by hihtcho** [comment]
Thank you your kindly reply
I temporaly treat the problem modifying the package source code pyarrow->parquet.py
(It may has some problem for treating URL of 'file////')
so, I inserted the following code in the function.
    ###############################################################
    if path_or_paths[0] == "/" :
        path_or_paths = path_or_paths[1:]
    ###############################################################

And reinstall pyspark=3.0.0  '-c conda-forge' for snappy problem

Thanks again.
